apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-prod
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s-app/podinfo/prod
  prune: true
  dependsOn:
    - name: podinfo-staging
  sourceRef:
    kind: GitRepository
    name: tf-aws-eks-flux-demo
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: podinfo-prod

