apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace is set by overlays (dev/staging/prod)
# Do not set namespace here to allow overlays to set it

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: podinfo
